[package]
name = "modules"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[profile.release]
# `lto = true` should also work
lto = 'fat'

[[bin]]
name = "modules"
path = "modules.rs"